# .readthedocs.yml

version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
conda:
  environment: doc/doc_env.yaml
